version: "3"


services:

  my-home-printer:
    image: ianstorm/my-home-printer:latest
    networks:
      - home-net
    ports:
      - 631:631
    privileged: true
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/

  my-smart-home-mqtt:
    image: ianstorm/my-smart-home-mqtt:latest
    networks:
      smart-home-net:
        aliases:
          - mqtt-broker
    ports:
      - 1883:1883

  my-smart-home-node-red:
    image: ianstorm/my-smart-home-node-red:latest
    depends_on:
      - my-smart-home-mqtt
      - my-smart-home-zigbee2mqtt
    env_file: ./credentials/docker-env.list
    networks:
      - smart-home-net
    ports:
      - 1880:1880

  my-smart-home-zigbee2mqtt:
    image: ianstorm/my-smart-home-zigbee2mqtt:latest
    depends_on:
      - my-smart-home-mqtt
    devices:
      - /dev/ttyACM0
    networks:
      - smart-home-net


networks:
  home-net:
  smart-home-net:
