version: "3"


services:

  my-home-printer:
    image: ianstorm/my-home-printer:latest
    ports:
      - 631:631
    privileged: true
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/

  my-smart-home-mqtt:
    image: ianstorm/my-smart-home-mqtt:latest
    networks:
      default:
        aliases:
          - mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001

  my-smart-home-node-red:
    image: ianstorm/my-smart-home-node-red:latest
    env_file: ./credentials/docker-env.list
    network_mode: host
    ports:
      - 1880:1880
    depends_on:
      - my-smart-home-mqtt
      - my-smart-home-zigbee2mqtt

  my-smart-home-zigbee2mqtt:
    image: ianstorm/my-smart-home-zigbee2mqtt:latest
    networks:
      - default
    devices:
      - /dev/ttyACM0
    depends_on:
      - my-smart-home-mqtt
