version: "3"


services:

  my-home-nginx:
    image: ianstorm/my-home-nginx:latest
    environment:
      - DNS_RESOLVER=127.0.0.11
      - MSH_MQTT_HOSTNAME=my-smart-home-mqtt
      - MSH_NODERED_HOSTNAME=my-smart-home-node-red
      - MSH_Z2M_HOSTNAME=my-smart-home-zigbee2mqtt
    ports:
      - 80:80

  my-home-status:
    image: ianstorm/my-home-status:latest
    env_file: ./credentials/status.env
    restart: always
    ports:
      - 8080:8080

  my-smart-home-mqtt:
    image: ianstorm/my-smart-home-mqtt:latest
    networks:
      smart-home-net:
        aliases:
          - mqtt-broker
    ports:
      - 1883:1883
      - 8083:8083

  my-smart-home-node-red:
    image: ianstorm/my-smart-home-node-red:latest
    depends_on:
      - my-smart-home-mqtt
      - my-smart-home-zigbee2mqtt
    env_file: ./credentials/docker-env.list
    networks:
      - smart-home-net
    ports:
      - 1880:1880

  my-smart-home-zigbee2mqtt:
    image: ianstorm/my-smart-home-zigbee2mqtt:latest
    depends_on:
      - my-smart-home-mqtt
    devices:
      - /dev/ttyUSB0
    networks:
      - smart-home-net
    ports:
      - 8099:8099
    volumes:
      - ./credentials/secret.yaml:/app/data/secret.yaml
      - /var/opt/my-smart-home-zigbee2mqtt/data/state.json:/app/data/state.json


networks:
  smart-home-net:
